// src/app/page/[slug]/page.tsx
import { getPageBySlug } from '@/lib/data'
import { notFound } from 'next/navigation'
import PublicModuleRenderer from '@/components/modules/PublicModuleRenderer'
import type { Metadata } from 'next'
import { EditorStateProvider } from '@/lib/editor/useEditorState'
import { PageContent } from '@/app/page'

export const dynamic = 'force-dynamic'

export async function generateMetadata({ params }: { params: { slug: string } }): Promise<Metadata> {
  const slug = params.slug
  console.log('🔍 Generating metadata for slug:', slug)
  const page = await getPageBySlug(slug)
  
  if (!page) {
    console.warn('⚠️ Page not found for metadata:', slug)
    return {
      title: 'Page Not Found',
      description: 'The requested page could not be found.',
    }
  }

  return {
    title: page.title || `Page: ${slug}`,
    description: page.description || 'Generated by Page.one',
  }
}

export default async function Page({ params, searchParams }: { params: { slug: string }, searchParams: { edit?: string } }) {
  const slug = params.slug
  console.log('📄 Loading page for slug:', slug)
  
  const page = await getPageBySlug(slug)
  const isEdit = searchParams.edit === 'true'

  if (!page) {
    console.error('❌ Page not found:', slug)
    notFound()
  }

  console.log('✅ Page loaded successfully:', {
    slug,
    hasModules: !!page.modules,
    moduleCount: page.modules?.length || 0
  })

  if (isEdit) {
    console.log('✏️ Loading edit mode')
    return (
      <EditorStateProvider initialModules={page.modules}>
        <PageContent />
      </EditorStateProvider>
    )
  }

  console.log('👁️ Loading public view')
  return (
    <EditorStateProvider initialModules={page.modules}>
      <main className="min-h-screen">
        <PublicModuleRenderer modules={page.modules} />
      </main>
    </EditorStateProvider>
  )
}
