// src/app/page/[slug]/page.tsx
import { getPageBySlug } from '@/lib/data'
import { notFound } from 'next/navigation'
import PublicModuleRenderer from '@/components/modules/PublicModuleRenderer'
import type { Metadata } from 'next'
import { EditorStateProvider } from '@/lib/editor/useEditorState'
import { PageContent } from '@/app/page'

export const dynamic = 'force-dynamic'

export async function generateMetadata({ params }: { params: { slug: string } }): Promise<Metadata> {
  const slug = params.slug
  const page = await getPageBySlug(slug)
  
  if (!page) {
    return {
      title: 'Page Not Found',
      description: 'The requested page could not be found.',
    }
  }

  return {
    title: page.title || `Page: ${slug}`,
    description: page.description || 'Generated by Page.one',
  }
}

export default async function Page({ params, searchParams }: { params: { slug: string }, searchParams: { edit?: string } }) {
  const slug = params.slug
  const page = await getPageBySlug(slug)
  const isEdit = searchParams.edit === 'true'

  if (!page) {
    notFound()
  }

  if (isEdit) {
    return (
      <EditorStateProvider initialModules={page.modules}>
        <PageContent />
      </EditorStateProvider>
    )
  }

  return (
    <EditorStateProvider initialModules={page.modules}>
      <main className="min-h-screen">
        <PublicModuleRenderer modules={page.modules} />
      </main>
    </EditorStateProvider>
  )
}
