// src/app/page/[slug]/page.tsx
import { getPageBySlug } from '@/lib/data'
import { notFound } from 'next/navigation'
import PublicModuleRenderer from '@/components/modules/PublicModuleRenderer'
import type { Metadata } from 'next'
import EditorPage from '@/components/editor/EditorPage'

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>
}): Promise<Metadata> {
  const { slug } = await params
  console.log('🔍 Generating metadata for slug:', slug)
  const page = await getPageBySlug(slug)
  
  if (!page) {
    console.warn('⚠️ Page not found for metadata:', slug)
    return {
      title: 'Page Not Found',
      description: 'The requested page could not be found.',
    }
  }

  return {
    title: page.title || `Page: ${slug}`,
    description: page.description || 'Generated by Page.one',
  }
}

export default async function Page({ 
  params,
  searchParams 
}: { 
  params: Promise<{ slug: string }>,
  searchParams: Promise<{ edit?: string, key?: string }>
}) {
  const { slug } = await params
  const { edit, key } = await searchParams
  
  console.log('📄 Loading page for slug:', slug, 'with key:', key ? 'present' : 'not present')
  
  try {
    const page = await getPageBySlug(slug, key)

    if (!page) {
      console.error('❌ Page not found:', slug)
      notFound()
    }

    console.log('✅ Page loaded successfully:', {
      slug,
      hasModules: !!page.modules,
      moduleCount: Array.isArray(page.modules) ? page.modules.length : 0
    })

    // If edit mode is requested, render the editor
    if (edit === 'true') {
      console.log('✏️ Loading edit mode')
      return <EditorPage modules={page.modules} />
    }

    // Otherwise render the public view
    console.log('👁️ Loading public view')
    return (
      <main className="min-h-screen bg-white">
        <PublicModuleRenderer modules={page.modules} />
      </main>
    )
  } catch (error) {
    console.error('❌ Error loading page:', error)
    throw error
  }
}
