import { Lead, Client } from './types';

export const dummyLeads: Lead[] = [
  {
    id: '1',
    name: 'Alice Smith',
    email: 'alice@example.com',
    phone: '555-1234',
    status: 'Uncontacted',
    assignedTo: '',
    source: 'Web Form',
    business: 'Smith Dental',
    notes: 'Interested in Google Ads.',
    appointmentDate: '',
    appointmentType: 'call',
    trialAgreed: false,
    lpReady: true,
    adwordsDeployed: false,
    gmbVerified: false,
  },
  {
    id: '2',
    name: 'Bob Johnson',
    email: 'bob@example.com',
    phone: '555-5678',
    status: 'Welcome Email',
    assignedTo: 'demo-user-uuid',
    source: 'Referral',
    business: 'Johnson Plumbing',
    notes: 'Follow up next week.',
    appointmentDate: '2024-07-01T10:00',
    appointmentType: 'zoom',
    trialAgreed: true,
    lpReady: true,
    adwordsDeployed: true,
    gmbVerified: false,
  },
  {
    id: '3',
    name: 'Carol Lee',
    email: 'carol@example.com',
    phone: '555-8765',
    status: 'Appointment Set',
    assignedTo: 'demo-user-uuid',
    source: 'Landing Page',
    business: 'Lee Consulting',
    notes: 'Onboarded, send welcome kit.',
    appointmentDate: '2024-07-03T14:30',
    appointmentType: 'in-person',
    trialAgreed: false,
    lpReady: false,
    adwordsDeployed: false,
    gmbVerified: true,
  },
  {
    id: '4',
    name: 'David Kim',
    email: 'david@example.com',
    phone: '555-4321',
    status: 'Converted',
    assignedTo: '',
    source: 'Web Form',
    business: 'Kim Electric',
    notes: 'Went with competitor.',
    appointmentDate: '',
    appointmentType: 'call',
    trialAgreed: true,
    lpReady: true,
    adwordsDeployed: true,
    gmbVerified: true,
  },
  {
    id: '5',
    name: 'Eva Green',
    email: 'eva@example.com',
    phone: '555-2468',
    status: 'Uncontacted',
    assignedTo: '',
    source: 'Event',
    business: 'Green Marketing',
    notes: '',
    appointmentDate: '',
    appointmentType: 'call',
    trialAgreed: false,
    lpReady: false,
    adwordsDeployed: false,
    gmbVerified: false,
  },
];

export const dummyClients: Client[] = [
  {
    id: 'c1',
    name: 'Frank Ocean',
    email: 'frank@ocean.com',
    phone: '555-9999',
    business: 'Ocean Consulting',
    notes: 'Converted from lead.',
    convertedFromLeadId: '4',
  },
  {
    id: 'c2',
    name: 'Grace Hopper',
    email: 'grace@hopper.com',
    phone: '555-8888',
    business: 'Hopper Tech',
    notes: 'VIP client.',
    convertedFromLeadId: '',
  },
]; 